version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    open-pull-requests-limit: 99
    labels:
      - "dependencies"
      - "automerge"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: 
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "automerge"
